name: Publish EMR Spark to Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  publish:
    runs-on: ai-platform-${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Publish to ECR (All Regions)
        uses: ./.github/actions/publish-emr-spark-to-env